### ISSUE TITLE
Question about expected semantic information gain.

### ISSUE THREAD

**Issue by Hymwgk** [akshaykburusa/gradientnbv#2]
I have some questions regarding the description of "expected semantic information gain" in the paper:

1. It seems that $I_s(ξ)$is the information value that a new viewpoint can obtain on the old grid. Why is it called "gain"? Am I misunderstanding something?
2. $I_s(ξ)$does not seem to emphasize different classes, such as focusing on fruit nodes specifically. Instead, it aims to make the semantic information within the FoV more certain. Is my understanding correct?
3. I noticed that the [ROI coverage](https://github.com/akshaykburusa/gradientnbv/blob/9c62530e6f13f4d16100cd4f331bc69184fd713a/src/viewpoint_planning/src/scene_representation/voxel_grid.py#L208C15-L208C28) is calculated, but it seems to be only for debugging purposes. The [compute_gain](https://github.com/akshaykburusa/gradientnbv/blob/9c62530e6f13f4d16100cd4f331bc69184fd713a/src/viewpoint_planning/src/scene_representation/voxel_grid.py#L210C8-L210C21) function appears to calculate the global expected information gain rather than the local gain for the ROI. Could you point out which part of the code specifically emphasizes the ROI area?

Thank you in advance for you help.

**Comment by akshaykburusa** [comment]
1. From information theory, `I_s(ξ)` is the Shannon's entropy. In our case, we intuitively understand it as the amount of information that is still unknown about the voxels that would be visible from a viewpoint, and hence it is the information that could be gained from the viewpoint if the camera was moved there.
2. Yes, that is correct. But you can easily emphasize one particular class, if you like. For this, in the [get_semantics](https://github.com/akshaykburusa/gradientnbv/blob/9c62530e6f13f4d16100cd4f331bc69184fd713a/src/viewpoint_planning/src/perception/segmentator.py#L88-L89) function, you can assign different log-odds values to the classes that your segmentation algorithm has detected or simply ignore the classes that are not of interest.
3. That's true. We used a more subtle way to emphasize the ROI. During initialization of the [voxel_grid](https://github.com/akshaykburusa/gradientnbv/blob/9c62530e6f13f4d16100cd4f331bc69184fd713a/src/viewpoint_planning/src/scene_representation/voxel_grid.py#L75-L87), we assigned a semantic confidence value close to zero for all the voxels. However, only for the voxels within the ROI, we set the semantic confidence value to 0.5 ([set_target_roi](https://github.com/akshaykburusa/gradientnbv/blob/9c62530e6f13f4d16100cd4f331bc69184fd713a/src/viewpoint_planning/src/scene_representation/voxel_grid.py#L284)). This ensures that the [compute_gain](https://github.com/akshaykburusa/gradientnbv/blob/9c62530e6f13f4d16100cd4f331bc69184fd713a/src/viewpoint_planning/src/scene_representation/voxel_grid.py#L210C8-L210C21) function gives preference to voxels within the ROI, because the voxels outside the ROI have very less information.
Alternately, you may directly use the ROI values when computing the gain, for example, by modifying the following lines in the compute_gain function:
```python
        ray_points_nor = self.normalize_3d_coordinate(ray_points)
        ray_points_nor = ray_points_nor.view(1, -1, 1, 1, 3).repeat(3, 1, 1, 1, 1)
        # Sample the occupancy probabilities and semantic confidences along each ray
        grid = self.voxel_grid[None, ..., 0:3].permute(4, 0, 1, 2, 3)
        occ_sem_confs = F.grid_sample(grid, ray_points_nor, align_corners=True)
        occ_sem_confs = occ_sem_confs.view(3, -1, self.num_pts_per_ray)
        occ_sem_confs = occ_sem_confs.clamp(self.eps, 1.0 - self.eps)
        # Compute the entropy of the semantic confidences along each ray
        opacities = torch.sigmoid(1e7 * (occ_sem_confs[1, ...] - 0.51))
        transmittance = self.shifted_cumprod(1.0 - opacities)
        ray_gains = (
            transmittance * self.entropy(occ_sem_confs[2, ...]) * occ_sem_confs[0, ...]
        )
```
The above lines interpolate the ROI values along the sampled points and then multiply them with the expected gain values. This should effectively make all the points that are not within the ROI zero. However, I have not tested how effective these changes are. Please check.

**Comment by Hymwgk** [comment]
Thanks again : )
